name: codemention
description: Mentions people who subscribe to file changes on pull requests
author: Toby Hsieh
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: node18
  main: dist/index.js
