name: codemention
description: Mentions people who subscribe to file changes on pull requests
author: Toby Hsieh

inputs:
  githubToken:
    required: true
    description: GitHub API token

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: ${{ github.action_path }}/node_modules
        key: codemention-npm
    - run: npm install
      working-directory: ${{ github.action_path }}
      shell: bash
    - run: npm run build
      working-directory: ${{ github.action_path }}
      shell: bash
    - run: node lib/main.js
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        INPUT_GITHUBTOKEN: "${{ inputs.githubToken }}"
